---
- name: Deploy Ecomm on node1 server
  hosts: node1
  become: yes

  tasks:
  - name: Install Git
    yum:
      name: git
      state: present

  - name: Deploy Code
    git:
      dest: /var/www/html
      repo: https://github.com/ravi2krishna/ecomm.git

...