---
- name: Setup apache2 on node2 server
  hosts: node2
  become: yes

  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present

  - name: Start apache2
    service:
      name: apache2
      state: started

  - name: Enable apache2
    service:
      name: apache2
      enabled: true 

...