---
- name: Deploy Info page on all server
  hosts: all
  become: yes
  vars:
    user_name: Akshay

  tasks:
  - name: copy Dynamic page
    template:
      src: info.j2
      dest: /var/www/html/dynamic.html
...